### ISSUE TITLE
Red status bar when no folder is opened

### ISSUE THREAD

**Issue by myakimov** [barrsan/reui-vscode-theme#3]
Hello,

I really like the theme you created! I just noticed one small issue that is visible only when a new window is open without any folders opened. The status bar is in red when opening the window. At the moment I open a folder it is not read anymore and colored as expected.

![image](https://user-images.githubusercontent.com/2385430/83503076-3a33a180-a4cb-11ea-95de-3922fbecbd11.png)

Checked locally, it seems those two colors are not set in the themes, after adding those, issue is fixed : 

    "statusBar.noFolderForeground": "#5884C9",
    "statusBar.noFolderBackground": "#18273a",

Best regards,
Marin

**Comment by barrsan** [comment]
Hello, Marin!
Thanks for issue and feedback! I fixed it. Check version 1.1.4.

**Comment by myakimov** [comment]
Looks great! Closing the issue.,

Thanks!
