### ISSUE TITLE
Can't disable italics

### ISSUE THREAD

**Issue by florianloechle** [barrsan/reui-vscode-theme#4]
Hey, thanks for the theme you created, I really like the colors!

Personally I don't like the italic fontstyle and currently seems no way to disable it in your theme. Can we add an option for this or publish a version of this theme without the italic fontstyle? 
Thanks a lot!

**Comment by barrsan** [comment]
Hey! Thanks for feedback! Sorry for late answer.

I added no-italic themes in version 1.2.0 https://github.com/barrsan/reui-vscode-theme/commit/a1f2a2c09ec52a70b307230672f117aab9500a82
